/* Auto-generated by genmsg_cpp for file /home/mafilipp/fuerte_workspace/sandbox/control_publisher/msg/control_message.msg */
#ifndef CONTROL_PUBLISHER_MESSAGE_CONTROL_MESSAGE_H
#define CONTROL_PUBLISHER_MESSAGE_CONTROL_MESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace control_publisher
{
template <class ContainerAllocator>
struct control_message_ {
  typedef control_message_<ContainerAllocator> Type;

  control_message_()
  : header()
  , psi(0.0)
  , phi(0.0)
  , theta(0.0)
  , thrust(0.0)
  {
  }

  control_message_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , psi(0.0)
  , phi(0.0)
  , theta(0.0)
  , thrust(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _psi_type;
  double psi;

  typedef double _phi_type;
  double phi;

  typedef double _theta_type;
  double theta;

  typedef double _thrust_type;
  double thrust;


  typedef boost::shared_ptr< ::control_publisher::control_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_publisher::control_message_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct control_message
typedef  ::control_publisher::control_message_<std::allocator<void> > control_message;

typedef boost::shared_ptr< ::control_publisher::control_message> control_messagePtr;
typedef boost::shared_ptr< ::control_publisher::control_message const> control_messageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::control_publisher::control_message_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::control_publisher::control_message_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace control_publisher

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::control_publisher::control_message_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::control_publisher::control_message_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::control_publisher::control_message_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2c697d3485b94c731573007cca1e49bb";
  }

  static const char* value(const  ::control_publisher::control_message_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2c697d3485b94c73ULL;
  static const uint64_t static_value2 = 0x1573007cca1e49bbULL;
};

template<class ContainerAllocator>
struct DataType< ::control_publisher::control_message_<ContainerAllocator> > {
  static const char* value() 
  {
    return "control_publisher/control_message";
  }

  static const char* value(const  ::control_publisher::control_message_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::control_publisher::control_message_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float64 psi\n\
float64 phi\n\
float64 theta\n\
float64 thrust\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::control_publisher::control_message_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::control_publisher::control_message_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::control_publisher::control_message_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::control_publisher::control_message_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.psi);
    stream.next(m.phi);
    stream.next(m.theta);
    stream.next(m.thrust);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct control_message_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_publisher::control_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::control_publisher::control_message_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROL_PUBLISHER_MESSAGE_CONTROL_MESSAGE_H

