/* Auto-generated by genmsg_cpp for file /home/mafilipp/fuerte_workspace/sandbox/control_publisher/msg/controller_out.msg */
#ifndef CONTROL_PUBLISHER_MESSAGE_CONTROLLER_OUT_H
#define CONTROL_PUBLISHER_MESSAGE_CONTROLLER_OUT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace control_publisher
{
template <class ContainerAllocator>
struct controller_out_ {
  typedef controller_out_<ContainerAllocator> Type;

  controller_out_()
  : header()
  , set_thrust(0.0)
  , set_phi(0.0)
  , set_theta(0.0)
  , set_psi(0.0)
  {
  }

  controller_out_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , set_thrust(0.0)
  , set_phi(0.0)
  , set_theta(0.0)
  , set_psi(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _set_thrust_type;
  double set_thrust;

  typedef double _set_phi_type;
  double set_phi;

  typedef double _set_theta_type;
  double set_theta;

  typedef double _set_psi_type;
  double set_psi;


  typedef boost::shared_ptr< ::control_publisher::controller_out_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_publisher::controller_out_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct controller_out
typedef  ::control_publisher::controller_out_<std::allocator<void> > controller_out;

typedef boost::shared_ptr< ::control_publisher::controller_out> controller_outPtr;
typedef boost::shared_ptr< ::control_publisher::controller_out const> controller_outConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::control_publisher::controller_out_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::control_publisher::controller_out_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace control_publisher

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::control_publisher::controller_out_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::control_publisher::controller_out_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::control_publisher::controller_out_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6f0b0c8f2a4eb2e2a2dd2b810666958b";
  }

  static const char* value(const  ::control_publisher::controller_out_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6f0b0c8f2a4eb2e2ULL;
  static const uint64_t static_value2 = 0xa2dd2b810666958bULL;
};

template<class ContainerAllocator>
struct DataType< ::control_publisher::controller_out_<ContainerAllocator> > {
  static const char* value() 
  {
    return "control_publisher/controller_out";
  }

  static const char* value(const  ::control_publisher::controller_out_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::control_publisher::controller_out_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header    header\n\
\n\
float64 set_thrust \n\
float64 set_phi\n\
float64 set_theta \n\
float64 set_psi \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::control_publisher::controller_out_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::control_publisher::controller_out_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::control_publisher::controller_out_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::control_publisher::controller_out_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.set_thrust);
    stream.next(m.set_phi);
    stream.next(m.set_theta);
    stream.next(m.set_psi);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct controller_out_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_publisher::controller_out_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::control_publisher::controller_out_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "set_thrust: ";
    Printer<double>::stream(s, indent + "  ", v.set_thrust);
    s << indent << "set_phi: ";
    Printer<double>::stream(s, indent + "  ", v.set_phi);
    s << indent << "set_theta: ";
    Printer<double>::stream(s, indent + "  ", v.set_theta);
    s << indent << "set_psi: ";
    Printer<double>::stream(s, indent + "  ", v.set_psi);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROL_PUBLISHER_MESSAGE_CONTROLLER_OUT_H

